version: '2'
services:
  blog:
    image: nginx:1.14
    container_name: blog
    expose:
      - 80
    volumes:
      - ./web/blog:/var/www/html/web
      - ./nginx/nginx-blog.conf:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: '/blog'

  profile:
    image: nginx:1.14
    container_name: profile
    expose:
      - 80
    volumes:
      - ./web/profile:/var/www/html/web
      - ./nginx/nginx-profile.conf:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: '/profile'

networks:
  default:
    external:
      name: sandbox_network